refactor: cleanup
le-phare/docker-apache pull request #5
Opened 2024-04-17 08:05 UTC by lucasmirloup

- remove legacy Apache 2.2
- build using Docker bake
- containers now stop immediately on SIGTERM
- stop using `jwilder/dockerize`
- lint using hadolint
- remove unused Brotli settings
- create CONTRIBUTING.md
- update README

2024-04-17 08:06 UTC, lucasmirloup commented
Hi @aegypius :wave:
Feel free to take a look and comment on the changes :+1:

2024-04-17 13:22 UTC, lucasmirloup commented
Note : I changed the default value of `DOCUMENT_ROOT` from `/var/www/symfony/web` to `/var/www/symfony/public` as this is [the default value since Symfony 4.x](https://symfony.com/doc/current/configuration/override_dir_structure.html#override-the-public-directory).

Developers using the updated image on Symfony <= 3.x projects will have to specify this in their `docker-compose.yml` :
```yaml
services:
  web:
    environment:
      DOCUMENT_ROOT: /var/www/symfony/web
```

2024-05-31 07:52 UTC, lucasmirloup commented
I reverted the change from `/var/www/symfony/web` to `/var/www/symfony/public` in order to avoid BC breaks in this PR.

2024-06-07 07:42 UTC, thislg requested changes

2024-06-07 07:42 UTC, thislg commented on virtualhost.conf
Put back brotli

2024-06-21 07:33 UTC, thislg approved these changes

2024-06-21 07:35 UTC, merged